# Generated by Django 4.2.30 on 2026-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="content_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of the uploaded file content.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("failed", "Failed"),
                    ("verification_failed", "Verification Failed"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="upload_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="upload_url_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the presigned upload URL expires.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
