# Generated by Django 4.2.30 on 2026-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_content_sha256_asset_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="embedding_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="embedding_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of the uploaded MobileSAM embedding file.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="embedding_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "Not Requested"),
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("failed", "Failed"),
                    ("verification_failed", "Verification Failed"),
                ],
                default="not_requested",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="embedding_upload_url_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="embedding_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="embedding_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
