# Generated by Django 4.2.30 on 2026-06-20 13:49

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_embedding_error_message_asset_embedding_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
