# Generated by Django 4.2.30 on 2026-06-20 13:49

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
