/**
 * SamCanvas.tsx
 *
 * Konva Layer for rendering the MobileSAM mask overlay and prompt indicators.
 *
 * ─── Mask Rendering ──────────────────────────────────────────────────────────
 * A semi-transparent blue overlay image is rendered at the original image
 * dimensions. The mask is a pre-colored PNG blob generated by the orchestrator
 * after cropping + scaling the model output.
 *
 * ─── Prompt Indicators ──────────────────────────────────────────────────────
 * Green filled dots  → positive prompts (left-click)
 * Red filled dots    → negative prompts (right-click)
 * Dot radius scales inversely with zoom level to maintain a consistent
 * screen-space size, matching the existing annotation tools' pattern.
 *
 * ─── Zoom/Pan Behavior ──────────────────────────────────────────────────────
 * Since this layer is a child of the Konva Stage, all coordinates are in
 * original image pixel space. The Stage's built-in transform (scale + position)
 * handles zoom and pan automatically. No special handling needed.
 *
 * ─── Integration ────────────────────────────────────────────────────────────
 * This component is intended to be rendered as a child of <Stage> inside
 * MainStage.tsx, positioned between <AnnotationLayer /> and <InteractionLayer />
 * so the mask appears above existing annotations but below the interaction surface.
 */

import React, { useEffect, useRef, useState } from 'react';
import { Layer, Image as KonvaImage, Circle, Rect } from 'react-konva';
import Konva from 'konva';
import { useAppStore } from '@/store/hooks/useAppStore';
import { useShallow } from 'zustand/react/shallow';
import type { SAMPrompt } from '../../types/annotation.types';

// ─── Constants ───────────────────────────────────────────────────────────────

/** Screen-space radius for prompt indicator dots (scaled inversely with zoom) */
const PROMPT_DOT_RADIUS = 6;

/** Colors for prompt indicators */
const PROMPT_COLORS = {
  positive: '#22c55e', // Green (matching annotation creation color)
  negative: '#ef4444', // Red
} as const;

/** Stroke color for prompt dot borders (always white for contrast) */
const PROMPT_STROKE_COLOR = '#ffffff';
const PROMPT_STROKE_WIDTH = 2;

// ─── Mask Image Component ────────────────────────────────────────────────────

/**
 * Internal component that loads a blob URL into a Konva-compatible HTML Image element.
 * This avoids using the `use-image` hook which has caching quirks with blob URLs.
 */
const MaskImage: React.FC<{
  maskBlobUrl: string | null;
  imageWidth: number;
  imageHeight: number;
}> = React.memo(({ maskBlobUrl, imageWidth, imageHeight }) => {
  const imageRef = useRef<HTMLImageElement | null>(null);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    if (!maskBlobUrl) {
      setLoaded(false);
      return;
    }

    const img = new window.Image();
    imageRef.current = img;

    img.onload = () => {
      setLoaded(true);
    };

    img.onerror = () => {
      console.warn('[SamCanvas] Failed to load mask blob URL:', maskBlobUrl);
      setLoaded(false);
    };

    img.src = maskBlobUrl;

    return () => {
      img.onload = null;
      img.onerror = null;
      // Do NOT revoke the object URL here — the orchestrator owns that lifecycle
    };
  }, [maskBlobUrl]);

  if (!loaded || !maskBlobUrl) return null;

  return (
    <KonvaImage
      image={imageRef.current!}
      x={0}
      y={0}
      width={imageWidth}
      height={imageHeight}
      listening={false} // The mask is purely visual; clicks pass through
      perfectDrawEnabled={false}
    />
  );
});

MaskImage.displayName = 'MaskImage';

// ─── Prompt Indicators ───────────────────────────────────────────────────────

/**
 * Renders prompt dots.
 * Extracted as a separate memoized component so it only re-renders when prompts change.
 */
const PromptIndicators: React.FC<{
  prompts: SAMPrompt[];
  scale: number;
}> = React.memo(({ prompts, scale }) => {
  return (
    <>
      {prompts.map((prompt, index) => (
        <Circle
          key={`prompt-${index}-${prompt.x.toFixed(0)}-${prompt.y.toFixed(0)}-${prompt.type}`}
          x={prompt.x}
          y={prompt.y}
          radius={PROMPT_DOT_RADIUS / scale}
          fill={PROMPT_COLORS[prompt.type]}
          stroke={PROMPT_STROKE_COLOR}
          strokeWidth={PROMPT_STROKE_WIDTH / scale}
          listening={false}
          perfectDrawEnabled={false}
        />
      ))}
    </>
  );
});

PromptIndicators.displayName = 'PromptIndicators';

// ─── Main Component ──────────────────────────────────────────────────────────

/**
 * SamCanvas — Konva Layer for SAM mask overlay + prompt indicators.
 *
 * Renders two layers of visual feedback:
 *   1. The mask (semi-transparent blue overlay from model output)
 *   2. Prompt dots (green=positive, red=negative)
 *
 * This component is only visible when the SAM tool is active. It's rendered
 * inside <Stage> in MainStage.tsx.
 */
export const SamCanvas: React.FC = () => {
  const { samMaskBlobUrl, samPrompts, samBboxPrompt, activeTool, imgDimensions, scale } =
    useAppStore(
      useShallow((state) => ({
        samMaskBlobUrl: state.samMaskBlobUrl,
        samPrompts: state.samPrompts,
        samBboxPrompt: state.samBboxPrompt,
        activeTool: state.activeTool,
        imgDimensions: state.imgDimensions,
        scale: state.scale,
      }))
    );

  // Only render when SAM tool is active and we have image dimensions
  if (activeTool !== 'sam' || !imgDimensions) return null;

  const hasVisibleContent = samMaskBlobUrl !== null || samPrompts.length > 0 || samBboxPrompt !== null;

  if (!hasVisibleContent) {
    // Render an empty Layer so the layer index stays consistent when switching tools.
    // This avoids an issue where Konva shifts layers when they are conditionally mounted.
    return <Layer listening={false} />;
  }

  return (
    <Layer listening={false}>
      {/* Mask overlay (semi-transparent blue PNG from orchestrator) */}
      {samMaskBlobUrl && (
        <MaskImage
          maskBlobUrl={samMaskBlobUrl}
          imageWidth={imgDimensions.width}
          imageHeight={imgDimensions.height}
        />
      )}

            {/* Prompt indicator dots */}
      {samPrompts.length > 0 && (
        <PromptIndicators prompts={samPrompts} scale={scale} />
      )}

      {/* BBox prompt indicator */}
      {samBboxPrompt && (
        <Rect
          x={Math.min(samBboxPrompt.x1, samBboxPrompt.x2)}
          y={Math.min(samBboxPrompt.y1, samBboxPrompt.y2)}
          width={Math.abs(samBboxPrompt.x2 - samBboxPrompt.x1)}
          height={Math.abs(samBboxPrompt.y2 - samBboxPrompt.y1)}
          stroke="#22c55e"
          strokeWidth={2 / scale}
          dash={[6 / scale, 4 / scale]}
          fill="rgba(34, 197, 94, 0.08)"
          listening={false}
          perfectDrawEnabled={false}
        />
      )}
    </Layer>
  );
};

SamCanvas.displayName = 'SamCanvas';
