# Generated by Django 4.2.30 on 2026-05-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("email", "Email"), ("msal", "Microsoft")],
                default="email",
                max_length=20,
            ),
        ),
    ]
