# Generated by Django 4.2.30 on 2026-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='msal_oid',
            field=models.CharField(blank=True, help_text='Microsoft Entra object ID (oid claim).', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='msal_tenant_id',
            field=models.CharField(blank=True, help_text='Microsoft Entra tenant ID (tid claim).', max_length=36, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('msal_oid__isnull', False), ('msal_tenant_id__isnull', False)), fields=('msal_tenant_id', 'msal_oid'), name='unique_msal_identity'),
        ),
    ]
