# Generated by Django 4.2.30 on 2026-05-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_asset_content_sha256_asset_status_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="task", old_name="description", new_name="note",
        ),
        migrations.RemoveField(model_name="task", name="assigned_to",),
        migrations.RemoveField(model_name="task", name="due_at",),
        migrations.RemoveField(model_name="task", name="title",),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("approval_pending", "Approval Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="assigned",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(name="TaskAsset",),
        migrations.AddField(
            model_name="taskimage",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_images",
                to="tasks.task",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskimage", unique_together={("task", "image")},
        ),
    ]
