# Generated by Django 4.2.30 on 2026-06-20 13:49

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskimage_rename_description_task_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
