# Generated by Django 4.2.30 on 2026-05-14 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPredicate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("include_in_export", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicates",
                        to="projects.project",
                    ),
                ),
            ],
            options={"ordering": ["name"], "unique_together": {("project", "name")},},
        ),
        migrations.CreateModel(
            name="ProjectClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Frontend display color, for example #FF0000.",
                        max_length=20,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Class index used for formats like YOLO."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("include_in_export", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["index", "name"],
                "unique_together": {("project", "name"), ("project", "index")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Used for select attributes. Example: ['red', 'blue', 'green']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("include_in_export", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="projects.project",
                    ),
                ),
            ],
            options={"ordering": ["name"], "unique_together": {("project", "name")},},
        ),
    ]
