# Generated by Django 4.2.30 on 2026-06-20 13:49

import apps.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattribute',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectclass',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectpredicate',
            name='id',
            field=models.UUIDField(default=apps.common.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
